
name: Check Jira Issue List

description: |
  This GitHub Action checks if a list of Jira issues is empty or not.

inputs:
  jira-issue-list:
    description: 'A list of Jira issues to check'
    required: true

outputs:
  result:
    description: 'The result of the Jira issue list check'
    value: ''

runs:
  using: 'node12'
  main: 'jirablocker.js'
  steps:
    - name: Check if Jira issue list is empty
      run: |
        const jiraIssueList = JSON.parse(process.env.INPUT_JIRA_ISSUE_LIST);
        if (jiraIssueList.length === 0) {
          console.log('::set-output name=result::go');
        } else {
          console.log('::set-output name=result::nogo');
        }
      env:
        INPUT_JIRA_ISSUE_LIST: ${{ inputs.jira-issue-list }}
