
name: My Action
description: My action description
inputs:
  jira_issues:
    description: 'Comma-separated list of Jira issues'
    required: true
runs:
  using: "node12"
  steps:
    - name: Check Jira Issues
      run: |
        const jiraIssues = JSON.parse(process.env.INPUT_JIRA_ISSUES);
        if (jiraIssues.length === 0) {
          console.log("No Jira issues found. Skipping further steps.");
          process.exit(0);
        } else {
          console.log("Jira issues found. Proceeding with further steps.");
          // Add your further steps here
        }
      env:
        INPUT_JIRA_ISSUES: ${{ toJson(inputs.jira_issues) }}
