
name: My Action
description: My action description
inputs:
  
outputs:
     description: 'if jira lis is empty then print('GO')else if list is non-empty then print('NOGO')
   
runs:
  using: 'node16'
  main: 'jirablocker.js'
