
name: Check Jira Issue List

description: |
  This GitHub Action checks if a list of Jira issues is empty or not.

inputs:
  jira-issue-list:
    description: 'A list of Jira issues to check'
    required: true

outputs:
  result:
    description: 'The result of the Jira issue list check'
    value: ''

runs:
  using: 'node12'
  steps:
    - name: Check if Jira issue list is empty
      run: |
        const jiraIssueList = JSON.parse(process.env.INPUT_JIRA_ISSUE_LIST);
        if (jiraIssueList.length === 0) {
          console.log("Jira issue list is empty");
          console.log("Setting output result to go");
          console.log("::set-output name=result::go");
        } else {
          console.log("Jira issue list is not empty");
          console.log("Setting output result to nogo");
          console.log("::set-output name=result::nogo");
        }
      env:
        INPUT_JIRA_ISSUE_LIST: ${{ toJson(inputs.jira-issue-list) }}
