
name: My Action
description: My action description
inputs:
  jira_url:
    description: 'The URL of the Jira instance'
    required: true
  jira_username:
    description: 'The username for the Jira account'
    required: true
  jira_api_token:
    description: 'The API token for the Jira account'
    required: true
  
outputs:
  jira_status:
    description: 'The status of the Jira list. Possible values are "GO" and "NOGO".'

runs:
  using: 'node16'
  main:
    script: 'jirablocker.js'
