name: Jira Blocker List
description: Lists Jira issues that are blockers
inputs:
  jira_url:
    description: 'The URL of the Jira instance'
    required: true
  jira_username:
    description: 'The username for the Jira account'
    required: true
  jira_api_token:
    description: 'The API token for the Jira account'
    required: true
outputs:
  blocker_list:
    description: 'A list of Jira issues that are blockers'
runs:
  using: node16
  main: jira.js

