
name: My Action
description: My action description
inputs:
  jira_url:
    description: 'The URL of the jira blocker list'
    required: true
  jira_username:
    description: 'The username for the Jira account'
    required: true
  jira_api_token:
    description: 'The API token for the Jira account'
    required: true
  jql:
    description: 'The JQL query used to filter JIRA issues.'
    required: true
   

  
outputs:
  go_no_go:
    description: 'Whether to proceed with the workflow or not. Can be "GO" or "NOGO"'


runs:
  using: 'node16'
  main: 'jirablocker.js'
    
