name: Extract Jira Issue IDs from Commit Comment
description: Extracts Jira issue IDs from the commit comment associated with a specific SHA.

inputs:
  github_url:
    description: 'The url for the commit comment with a specific SHA'
    required: true
 
outputs:
  jira-issue-ids:
    description: 'A comma-separated list of Jira issue IDs found in the commit comment.'

runs:
  using: 'node12'
  main: 'defectid.js'
  
