name: 'Print Message'
description: 'Prints a message to the console'
inputs:
  message:
    description: 'The message to print'
    required: true
runs:
  using: 'composite'
   steps:
    - name: Print Message
      run: echo "Hello, world!"

