name: Jira Issue Labeler
description: This action compares a commit comment defect ID with a Jira issue key, and if they match, it adds a label to the corresponding Jira issue.
inputs:
  github_url:
    description: 'The url for commit comment .'
    required: true
  jira_issue_key:
    description: 'The Jira issue key to compare the commit comment defect ID against.'
    required: true
  jira_url:
    description: 'The URL of the Jira instance.'
    required: true
  jira_username:
    description: 'The username to use to authenticate with the Jira API.'
    required: true
  jira_api_token:
    description: 'The API token to use to authenticate with the Jira API.'
    required: true
  jira_label:
    description: 'The label to add to the Jira issue if the commit comment defect ID matches the Jira issue key.'
    required: true

runs:
  using: 'node16'
  main: 'jiraissueaddlabel.js'
