name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://swgup.atlassian.net/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
         curl --request POST \
         --url 'https://swgup.atlassian.net/rest/api/2/search/issue
          --user 'swatig139@gmail.com:<api_token>' \
            --header 'Accept: application/json' \
         --header 'Content-Type: application/json' \
