name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://swgup.atlassian.net/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
      
           curl --request POST \
           --url 'https://swgup.atlassian.net/rest/api/3/search' \
           --user 'swatg139@gmail.com:<$secrets.JIRA_API_TOKEN>' \
           --header 'Accept: application/json' \
           --header 'Content-Type: application/json' \
           --data '{
            "expand": [
             "names",
            "schema",
           "operations"
                 ],
             "fields": [
             "summary",
               "status",
               "assignee"
                  ],
               "fieldsByKeys": true,
             "jql": "filter = allissues",
              "maxResults": 15,
               "startAt": 0
                  }'
