name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://swgup.atlassian.net/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
         curl --request POST \
         --url 'curl -X GET \
             -H "Authorization: Bearer <your-access-token>" \
             -H "Content-Type: application/json" \
             "https://swgup.atlassian.net/rest/api/2/search?filter=allissues&startAt=0&maxResults=50&fields=summary,status,description"
         
         
