name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://swgup.atlassian.net/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
      
           curl -X GET \
           -H "Authorization: Bearer $JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
           "https://swgup.atlassian.net/rest/api/2/search?filter=-4&jql=ORDER%20BY%20assignee%20DESC%2C%20created%20DESC"

        
