name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Get JIRA Blocker List
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: |
          npm install
          npm install xmlhttprequest
      - name: Retrieve JIRA Blocker List
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: node jira.js --token $JIRA_API_TOKEN

     
     
