name: Get JIRA Blocker List

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get JIRA Blocker List
        uses: ./Myaction3
        with:
          jira_username: ${{ secrets.JIRA_USERNAME }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
      - name: Print Blocker List
        run: echo "${{ steps.get-jira-blocker-list.outputs.blocker_list }}"

       
    
     
      
       

     
     
