name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://your-jira-instance.atlassian.net/rest/api/2/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
        curl -H "Authorization: Basic $(echo -n $JIRA_API_TOKEN | base64)" \
             -H "Content-Type: application/json" \
             $JIRA_API_ENDPOINT/search?jql=issueType=Blocker > blocker_list.json
