name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment variables
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          echo "Username: $JIRA_USERNAME"
          echo "API Token: $JIRA_API_TOKEN"
      - name: Install dependencies
        run: npm install xhr2
      - name: Get JIRA Blocker List
        uses: actions/checkout@v2
      - uses: ./Myaction3


     
     
