name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://swgup.atlassian.net/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
         run: |
           curl -X GET \
          -H "Authorization: Bearer $JIRA_API_TOKEN" \
          -H "Content-Type: application/json" \
          "$JIRA_API_ENDPOINT/rest/api/2/search/issue?jql=project=SWT"
        
