name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
      - name: Get JIRA Blocker List
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Set JIRA username and API token
        env:
          JIRA_USERNAME: swatig139@gmail.com
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: echo "JIRA_USERNAME=$JIRA_USERNAME JIRA_API_TOKEN=$JIRA_API_TOKEN"
      - name: Install dependencies
        run: |
          npm install
          
          npm install xmlhttprequest
          npm install dotenv
      - name: Retrieve JIRA Blocker List
       
        run: node jira.js 

     
     
