name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
      env:
        JIRA_API_ENDPOINT: https://swgup.atlassian.net/
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      run: |
      
          curl -D- -u swatig139@gmail.com:${{ secrets.JIRA_API_TOKEN }}-X GET -H "Content-Type: application/json" https://swgup.atlassian.net/rest/api/3/search?filter=allissues
         
