name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
    - name: Get JIRA Blocker List
    -  uses: actions/checkout@v3
    -  env:
         JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
       run: |
         npm install
         npm install xmlhttprequest
         node jira.js
     
     
