name: Get JIRA Blocker List
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  get-blocker:
    runs-on: ubuntu-latest
    steps:
     
      - name: Get JIRA Blocker List
        uses: actions/checkout@v2
      - name: Debug
        run: echo "URL is ${{ github.event.inputs.url }}"
      - name: My action
        uses: ./blockerlist
        with:
         url: ${{ github.event.inputs.url }}
        env: 
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          

     
     
