name: CommitComment

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  commit_comments:
    runs-on: ubuntu-latest

    steps:
    - name: Commit
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         curl -L \
         -X GET \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer <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>"\
             https://api.github.com/repos/SiyaaJhawar/action/git/commits/b63d854b9c2d60ba843e7da1106c8076fe203704
       
       
