name: jirablockernogo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: My action
        uses: ./JIRAissueGONOGO
        with:
          jira_url: '
          jql: 'project=SWT AND filter=10003'
        env: 
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
