name: jirablockernogo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: My action
        uses: ./Jirablockerissue
        with:
          jira_url: 'https://swgup.atlassian.net/rest/api/3/search?jql=project=SWT AND filter=10001'
         
        env: 
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
