name: jiraissueaddlabel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  myJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -  name: my action
     
         uses: ./jiraissuelabel
         with:
         github_url: '
         env:
         
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
