name: 'My Reusable Workflow'

on:

 workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SiyaaJhawar/action/myaction@main
      - uses: SiyaaJhawar/action/myaction1@main
      
      
       
      


      
        
    
     
