name: 'My Reusable Workflow'

on:

  workflow_call:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v2
      - name: 'Run My Action'
        uses: './action'
        with:
          message: 'Hello, world!'
