name: 'My Reusable Workflow'

on:

  workflow_call:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run My action
        uses: SiyaaJhawar/action/myaction@main
      


      
        
    
     
