name: 'My Reusable Workflow'

on:

 workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: action1
      - uses: actions/checkout@v2
      - uses: SiyaaJhawar/action/action.yml@main
      
      
      
       
      


      
        
    
     
