name: Call a reusable workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  call-workflow:
    uses: SiyaaJhawar/action/.github/workflows/reusable.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
